name: catt
version: '0.4.1'
summary: cli chromecast streamer
description: |
  Controls your cromecast from the console.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  catt:
    command: wrapper
    plugs: [network, network-bind]

parts:
  catt:
    source: https://github.com/skorokithakis/catt.git
    plugin: python

  wrapper:
    plugin: dump
    source: .
    filesets:
      wrapper: wrapper
